name: "Release VPMPackage by Pushing Tag"

on:
  push:
    tags:
      - v\d+\.\d+\.\d+
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.vars.outputs.version }}
    steps:
      - id: vars
        run: |
          VERSION=$(echo ${{ github.ref }} | sed -e 's/refs\/tags\///' | sed -e 's/refs\/heads\///')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

  packaging:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: false

      - run: |
          git config --global credential.https://git-lfs.natsuneko.moe.username $GITHUB_ACTOR
          git config --global credential.https://git-lfs.natsuneko.moe.helper '!f() { test "$1" = get && echo "password=$GITHUB_TOKEN"; }; f'
          git config --global lfs.repositoryformatversion 0
          git config --global lfs.https://git-lfs.natsuneko.moe/$GITHUB_REPOSITORY/.access basic
          git config --global lfs.https://git-lfs.natsuneko.moe/$GITHUB_REPOSITORY/.locksverify false

          git lfs install
          git lfs pull
        env:
          GIT_CURL_VERBOSE: 1
          GIT_TRACE: 1
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          mkdir ./dist

      - uses: natsuneko-laboratory/create-vpmpackage@main
        with:
          package: Assets/NatsunekoLaboratory/AssetLens/package.json
          output: dist/cat.natsuneko.asset-lens-${{ needs.setup.outputs.version }}.zip

      - uses: actions/upload-artifact@v2
        with:
          name: AssetLens
          path: ./dist
